var searchData=
[
  ['random_5faccess_5fiterator_5ftag',['random_access_iterator_tag',['../structgxx_1_1random__access__iterator__tag.html',1,'gxx']]],
  ['random_5faccess_5fiterator_5ftag',['random_access_iterator_tag',['../structstd_1_1random__access__iterator__tag.html',1,'std']]],
  ['range',['range',['../classgxx_1_1gen_1_1range.html',1,'gxx::gen']]],
  ['rank',['rank',['../structrank.html',1,'']]],
  ['rank_3c_20t_5b_5d_3e',['rank&lt; T[]&gt;',['../structrank_3_01T[]_4.html',1,'']]],
  ['rank_3c_20t_5bn_5d_3e',['rank&lt; T[N]&gt;',['../structrank_3_01T[N]_4.html',1,'']]],
  ['rdm_5fsocket',['rdm_socket',['../structgxx_1_1inet_1_1rdm__socket.html',1,'gxx::inet']]],
  ['reader',['reader',['../structgxx_1_1io_1_1reader.html',1,'gxx::io']]],
  ['reader',['reader',['../classgxx_1_1reader.html',1,'gxx']]],
  ['readline',['readline',['../classgxx_1_1readline.html',1,'gxx']]],
  ['reference_5fwrapper',['reference_wrapper',['../classreference__wrapper.html',1,'']]],
  ['remove_5fall_5fextents',['remove_all_extents',['../structremove__all__extents.html',1,'']]],
  ['remove_5fall_5fextents_3c_20t_5b_5d_3e',['remove_all_extents&lt; T[]&gt;',['../structremove__all__extents_3_01T[]_4.html',1,'']]],
  ['remove_5fall_5fextents_3c_20t_5bn_5d_3e',['remove_all_extents&lt; T[N]&gt;',['../structremove__all__extents_3_01T[N]_4.html',1,'']]],
  ['remove_5fconst',['remove_const',['../structremove__const.html',1,'']]],
  ['remove_5fconst_3c_20const_20t_20_3e',['remove_const&lt; const T &gt;',['../structremove__const_3_01const_01T_01_4.html',1,'']]],
  ['remove_5fcv',['remove_cv',['../structremove__cv.html',1,'']]],
  ['remove_5fextent',['remove_extent',['../structremove__extent.html',1,'']]],
  ['remove_5fextent_3c_20t_5b_5d_3e',['remove_extent&lt; T[]&gt;',['../structremove__extent_3_01T[]_4.html',1,'']]],
  ['remove_5fextent_3c_20t_5bn_5d_3e',['remove_extent&lt; T[N]&gt;',['../structremove__extent_3_01T[N]_4.html',1,'']]],
  ['remove_5freference',['remove_reference',['../structremove__reference.html',1,'']]],
  ['remove_5freference_3c_20t_20_26_20_3e',['remove_reference&lt; T &amp; &gt;',['../structremove__reference_3_01T_01_6_01_4.html',1,'']]],
  ['remove_5freference_3c_20t_20_26_26_20_3e',['remove_reference&lt; T &amp;&amp; &gt;',['../structremove__reference_3_01T_01_6_6_01_4.html',1,'']]],
  ['remove_5fvolatile',['remove_volatile',['../structremove__volatile.html',1,'']]],
  ['remove_5fvolatile_3c_20volatile_20t_20_3e',['remove_volatile&lt; volatile T &gt;',['../structremove__volatile_3_01volatile_01T_01_4.html',1,'']]],
  ['result',['result',['../structhalf__float_1_1detail_1_1result.html',1,'half_float::detail']]],
  ['result',['result',['../classgxx_1_1result__type_1_1result.html',1,'gxx::result_type']]],
  ['result_3c_20half_2c_20half_20_3e',['result&lt; half, half &gt;',['../structhalf__float_1_1detail_1_1result_3_01half_00_01half_01_4.html',1,'half_float::detail']]],
  ['result_3c_20void_2c_20e_20_3e',['result&lt; void, E &gt;',['../structgxx_1_1result__type_1_1result_3_01void_00_01E_01_4.html',1,'gxx::result_type']]],
  ['result_5fof',['result_of',['../structresult__of.html',1,'']]],
  ['result_5fof',['result_of',['../structdetail_1_1result__of.html',1,'detail']]],
  ['result_5fof_3c_20f_28argtypes_2e_2e_2e_29_3e',['result_of&lt; F(ArgTypes...)&gt;',['../structdetail_1_1result__of.html',1,'detail::result_of&lt; F(ArgTypes...)&gt;'],['../structresult__of_3_01F_07ArgTypes_8_8_8_08_4.html',1,'result_of&lt; F(ArgTypes...)&gt;']]],
  ['reverse_5fiterator',['reverse_iterator',['../classgxx_1_1dlist_1_1reverse__iterator.html',1,'gxx::dlist']]],
  ['ring',['ring',['../classgxx_1_1ring.html',1,'gxx']]],
  ['ring_3c_20gxx_3a_3agxx_3a_3adelegate_3c_20void_2c_20args_2e_2e_2e_20_3e_20_3e',['ring&lt; gxx::gxx::delegate&lt; void, Args... &gt; &gt;',['../classgxx_1_1ring.html',1,'gxx']]],
  ['ring_3c_20gxx_3a_3agxx_3a_3asmart_5fbuffer_20_3e',['ring&lt; gxx::gxx::smart_buffer &gt;',['../classgxx_1_1ring.html',1,'gxx']]],
  ['ring_5fhead',['ring_head',['../structring__head.html',1,'']]],
  ['ringbuffer',['ringbuffer',['../classgxx_1_1io_1_1ringbuffer.html',1,'gxx::io']]],
  ['ringstrm',['ringstrm',['../classgxx_1_1io_1_1ringstrm.html',1,'gxx::io']]],
  ['rshift',['rshift',['../structlinalg_1_1op_1_1rshift.html',1,'linalg::op']]]
];
